version: '3.7'
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf:/etc/nginx/conf.d
      - /data/projects/SaiWin/prod/www:/etc/nginx/html/www
    ports:
      - 8088:80
    networks:
      - overnet
  biziedge:
    depends_on:
      - mongo
    image: 'biziedge'
    environment:
      - MONGO_URI=mongodb://10.1.1.110:11018/BiziEdge
      - USER=xxxx
      - PASSWORD=xxxx
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: "60s"
      timeout: "3s"
      start_period: "5s"
      retries: 3
    networks:
      - overnet
    ports:
      - 10000:5000
  mongo:
    image: 'mongo'
    environment:
      - MONGO_INITDB_DATABASE=BiziEdge
      - MONGO_NON_ROOT_USERNAME=admin
      - MONGO_NON_ROOT_PASSWORD=admin
    volumes:
      - /data/projects/SaiWin/prod/mongo-volume:/data/db
    networks:
        - overnet
    ports:
      - 11018:27017
networks:
  overnet:
    driver: overlay
    attachable: true
