var express = require("express");
var router = express.Router();
var userRouter = require("./user-router");
var roleRouter = require("./role-router");
var categoryRouter = require("./category-router");
var beatRouter = require("./beat-router");
var manufacturerRouter = require("./manufacturer-router");
var vehicleRouter = require("./vehicle-router");
var accessPolicyRouter = require("./access-policy-router");
var resourceRouter = require("./resource-router");
var actionRouter = require("./action-router");
var brandRouter = require("./brand-router");
var plgRouter = require("./plg-router");
var productRouter = require("./product-router");
var quantityNormRouter = require("./quantity-norm-router");
var inventoryRouter = require("./inventory-router");
var facilityRouter = require("./facility-router");
var orderRouter = require("./order-router");
var orderStatusRouter = require("./order-status-router");
var accessMatrixRouter = require("./access-matrix-router");
var hsnGstRouter = require("./hsn-gst-router");
var schemeRouter = require("./scheme-router");
var businessRouter = require("./business-router");
var menuItemRouter = require("./menu-item-router");
var returnRouter = require("./return-router");
var leadRouter = require("./lead-router");
var assignTask = require("./assign-beat-router");
var menuRoleMapRouter = require("./menu-role-map-router");
var facilityMapRouter = require("./facility-map-router");
var draftBillRouter = require("./draft-bill-router");
var supplierRouter = require("./supplier-router");
var expiryProductRouter = require("./expiry-product-router");
var inventoryLedgerRouter = require("./inventory-ledger-router");
var taxRouter = require("./tax-router");
var stateRouter = require("./state-router");
var countryRouter = require("./country-router");
var stockMismatchReasonRouter = require("./stock-mismatch-reason-router");
var targetRouter = require("./target-router");
var salesPersonRouter = require("./seles-person-router");
var schemeVariableRouter = require("./scheme-varibale-router");
var effectVariableRouter = require("./effect-variable-router");
var cartRouter = require("./cart-router");
var couponRouter = require("./coupon-router");
var keywordRouter = require("./keyword-router");
var addressRouter = require("./address-router");
var orderFeedbackRouter = require("./order-feedback-router");
var deviceTokenRouter = require("./device-token-router");
var notificationRouter = require("./notification-router");
var landingPage = require("./landing-page-router");
var slide = require("./slide-router");
var staticDataRouter = require("./static-data-router");

router.use("/user", userRouter);
router.use("/role", roleRouter);
router.use("/category", categoryRouter);
router.use("/beat", beatRouter);
router.use("/manufacturer", manufacturerRouter);
router.use("/vehicle", vehicleRouter);
router.use("/access-policy", accessPolicyRouter);
router.use("/resource", resourceRouter);
router.use("/action", actionRouter);
router.use("/brand", brandRouter);
router.use("/pricelist-group", plgRouter);
router.use("/product", productRouter);
router.use("/quantity-norm", quantityNormRouter);
router.use("/inventory", inventoryRouter);
router.use("/facility", facilityRouter);
router.use("/order", orderRouter);
router.use("/order-status", orderStatusRouter);
router.use("/access-matrix", accessMatrixRouter);
router.use("/hsn-gst", hsnGstRouter);
router.use("/scheme", schemeRouter);
router.use("/business", businessRouter);
router.use("/menu-item", menuItemRouter);
router.use("/return", returnRouter);
router.use("/lead", leadRouter);
router.use("/assigned-beat", assignTask);
router.use("/menu-role-map", menuRoleMapRouter);
router.use("/facility-map", facilityMapRouter);
router.use("/draft-bill", draftBillRouter);
router.use("/supplier", supplierRouter);
router.use("/expiryProduct", expiryProductRouter);
router.use("/inventoryLedger", inventoryLedgerRouter);
router.use("/tax", taxRouter);
router.use("/country", countryRouter);
router.use("/state", stateRouter);
router.use("/stock-mismatch-reason", stockMismatchReasonRouter);
router.use("/target", targetRouter);
router.use("/sales-person", salesPersonRouter);
router.use("/scheme-variable", schemeVariableRouter);
router.use("/effect-variable", effectVariableRouter);
router.use("/cart", cartRouter);
router.use("/coupon", couponRouter);
router.use("/keywords", keywordRouter);
router.use("/address", addressRouter);
router.use("/order-feedback", orderFeedbackRouter);
router.use("/device", deviceTokenRouter);
router.use("/notification", notificationRouter);
router.use("/landing-page", landingPage);
router.use("/slide", slide);
router.use("/static-data", staticDataRouter);

module.exports = router;
